export type Language = 'pt' | 'en' | 'ar';

export const translations = {
  pt: {
    header: { about: "Sobre", specialties: "Especialidades", howItWorks: "Como Funciona", testimonials: "Depoimentos", whatsapp: "Falar no WhatsApp" },
    hero: { badge: "Referência em São Bernardo do Campo", title1: "Especialistas em", titleHighlight: "Mecânica Geral", title2: "e Todos os Tipos de Câmbio", description: "Mais de 30 anos de experiência com diagnóstico preciso, transparência e garantia para o seu veículo. Especialistas em motores e todos os sistemas de câmbio (Manual, Automático, DSG, Easytronic, etc).", list1: "🔧 Mecânica Geral", list2: "⚙️ Manual • Automático • CVT • DSG • Dualogic", list3: "🚗 Nacionais e Importados", quoteBtn: "Fazer orçamento no WhatsApp", locationBtn: "Como chegar", feature1: "Excelente avaliação Google", feature2: "Garantia dos serviços", feature3: "Atendimento transparente", feature4: "Diagnóstico especializado" },
    about: { title1: "Quem é a", titleHighlight: "Alnajar?", p1: "Somos uma oficina modelo em São Bernardo do Campo, especializada em **mecânica geral avançada** e em **todos os tipos de câmbio** (Manual, Automático, DSG, Easytronic, PowerShift, CVT, I-Motion). Nossa missão é mudar a forma como você cuida do seu carro, trazendo um padrão premium com preços justos.", p2: "Nossas raízes são **árabes**, e trazemos conosco a verdadeira cultura da **excelência, honra e hospitalidade**. A Alnajar é um ambiente familiar, onde todos que trabalham aqui são da família. Tratamos nossos clientes como convidados em nossa própria casa e cuidamos do seu veículo como se fosse nosso.", p3: "Trabalhamos com os pilares da **honestidade, transparência e qualidade técnica**. Aqui, você não tem surpresas: realizamos um diagnóstico computadorizado preciso e o orçamento é explicado detalhadamente pelo WhatsApp.", feat1: "Diagnóstico 100% preciso e transparente", feat2: "Garantia total em peças e mão de obra", feat3: "Atendimento caloroso e familiar (Tradição Árabe)", videoTitle: "Acompanhe pelo WhatsApp", videoDesc: "Enviamos vídeos de cada etapa do serviço." },
    cta: { title1: "Seu carro merece", titleHighlight: "especialistas.", description: "Pare de ser enganado por oficinas comuns. Traga seu carro para a família Alnajar e sinta a diferença da verdadeira hospitalidade árabe unida à excelência mecânica. Garantimos a solução definitiva para o seu veículo.", btn: "Falar no WhatsApp" },
    specialties: { title1: "Nossas", titleHighlight: "Especialidades", desc: "De diagnósticos complexos de eletrônica embarcada à retífica de motores e todos os tipos de câmbios (manuais e automáticos). Nossa equipe resolve qualquer desafio." },
    testimonials: { title1: "O que dizem", titleHighlight: "nossos clientes", desc: "A satisfação de quem já confiou o carro à Mecânica Alnajar.", customer: "Cliente Alnajar" },
    stats: { years: "Anos de Tradição", clients: "Clientes Satisfeitos", rating: "Avaliação Google", guarantee: "Dias de Garantia" },
    faq: { title1: "Perguntas", titleHighlight: "Frequentes", desc: "Tire suas dúvidas sobre nossos serviços e garantias." },
    differentials: { title1: "Por que escolher a", titleHighlight: "Alnajar?", desc: "Nossa cultura árabe nos ensina a tratar cada cliente como um convidado de honra." },
    howItWorks: { title1: "Como", titleHighlight: "Funciona", desc: "Um processo transparente do início ao fim." }
  },
  en: {
    header: { about: "About", specialties: "Specialties", howItWorks: "How it Works", testimonials: "Testimonials", whatsapp: "Contact WhatsApp" },
    hero: { badge: "Reference in São Bernardo do Campo", title1: "Specialists in", titleHighlight: "Automatic Transmission", title2: "& General Mechanics", description: "Over 30 years of experience offering precise diagnosis, transparency, and guaranteed services for your vehicle. Tradition and excellence in every detail.", list1: "🔧 General Mechanics", list2: "⚙️ Manual • Automatic • CVT • DSG • Dualogic", list3: "🚗 National & Imported", quoteBtn: "Request a quote", locationBtn: "How to get here", feature1: "Excellent Google rating", feature2: "Service warranty", feature3: "Transparent service", feature4: "Specialized diagnosis" },
    about: { title1: "Who is", titleHighlight: "Alnajar?", p1: "We are a model workshop in São Bernardo do Campo, specialized in **manual & automatic transmissions** and **advanced general mechanics**. Our mission is to change the way you care for your car, bringing a premium standard at fair prices.", p2: "Our roots are **Arab**, and we bring with us the true culture of **excellence, honor, and hospitality**. Alnajar is a family environment, where everyone working here is family. We treat our clients like guests in our own home and care for your vehicle as if it were ours.", p3: "We operate on the pillars of **honesty, transparency, and technical quality**. Here, there are no surprises: we perform precise computerized diagnostics and the estimate is explained in detail.", feat1: "100% precise and transparent diagnosis", feat2: "Full warranty on parts and labor", feat3: "Warm and family-oriented service (Arab Tradition)", videoTitle: "Follow along on WhatsApp", videoDesc: "We send videos of every step of the service." },
    cta: { title1: "Your car deserves", titleHighlight: "specialists.", description: "Stop getting fooled by ordinary repair shops. Bring your car to the Alnajar family and feel the difference of true Arab hospitality combined with mechanical excellence. We guarantee the definitive solution for your vehicle.", btn: "Contact WhatsApp" },
    specialties: { title1: "Our", titleHighlight: "Specialties", desc: "From complex electronic diagnostics to engine overhauls and all types of transmissions (manual & automatic). Our team solves any challenge." },
    testimonials: { title1: "What", titleHighlight: "our clients say", desc: "The satisfaction of those who trusted their car to Alnajar Mechanics.", customer: "Alnajar Client" },
    stats: { years: "Years of Tradition", clients: "Satisfied Clients", rating: "Google Rating", guarantee: "Days of Warranty" },
    faq: { title1: "Frequently", titleHighlight: "Asked Questions", desc: "Clear your doubts about our services and warranties." },
    differentials: { title1: "Why choose", titleHighlight: "Alnajar?", desc: "Our Arab culture teaches us to treat every client as an honored guest." },
    howItWorks: { title1: "How it", titleHighlight: "Works", desc: "A transparent process from start to finish." }
  },
  ar: {
    header: { about: "من نحن", specialties: "تخصصاتنا", howItWorks: "كيف نعمل", testimonials: "آراء العملاء", whatsapp: "تواصل عبر واتساب" },
    hero: { badge: "المرجع في ساو برناردو دو كامبو", title1: "متخصصون في", titleHighlight: "ناقل الحركة الأوتوماتيكي", title2: "والميكانيكا العامة", description: "أكثر من 30 عامًا من الخبرة في تقديم تشخيص دقيق وشفافية وخدمات مضمونة لسيارتك. التقاليد والتميز في كل التفاصيل.", list1: "🔧 ميكانيكا عامة", list2: "⚙️ عادي • أوتوماتيكي • CVT • DSG • Dualogic", list3: "🚗 محلي ومستورد", quoteBtn: "طلب عرض سعر", locationBtn: "كيف تصل إلينا", feature1: "تقييم ممتاز على جوجل", feature2: "ضمان الخدمات", feature3: "خدمة شفافة", feature4: "تشخيص متخصص" },
    about: { title1: "من هي", titleHighlight: "النجار؟", p1: "نحن ورشة نموذجية في ساو برناردو دو كامبو، متخصصون في **ناقل الحركة العادي والأوتوماتيكي** و**الميكانيكا العامة المتقدمة**. مهمتنا هي تغيير طريقة العناية بسيارتك، وتقديم معيار متميز بأسعار عادلة.", p2: "جذورنا **عربية**، ونحمل معنا الثقافة الحقيقية **للتميز والشرف والضيافة**. النجار هي بيئة عائلية، حيث كل من يعمل هنا هم من العائلة. نحن نعامل عملائنا كضيوف في منزلنا ونهتم بسيارتك وكأنها سيارتنا.", p3: "نحن نعمل على ركائز **الصدق والشفافية والجودة الفنية**. هنا، لا توجد مفاجآت: نقوم بإجراء تشخيصات دقيقة محوسبة ويتم شرح التكلفة بالتفصيل.", feat1: "تشخيص دقيق وشفاف بنسبة 100٪", feat2: "ضمان كامل على قطع الغيار والعمل", feat3: "خدمة دافئة وعائلية (تقاليد عربية)", videoTitle: "تابعنا عبر الواتساب", videoDesc: "نرسل مقاطع فيديو لكل خطوة من خطوات الخدمة." },
    cta: { title1: "سيارتك تستحق", titleHighlight: "متخصصين.", description: "توقف عن الانخداع بورش الإصلاح العادية. أحضر سيارتك إلى عائلة النجار واشعر بالفرق في الضيافة العربية الحقيقية مع التميز الميكانيكي. نضمن لك الحل النهائي لسيارتك.", btn: "تواصل عبر واتساب" },
    specialties: { title1: "تخصصاتنا", titleHighlight: "الرئيسية", desc: "من تشخيص الإلكترونيات المعقدة إلى إصلاح المحركات وجميع أنواع نواقل الحركة (العادية والأوتوماتيكية). فريقنا يحل أي تحدٍ." },
    testimonials: { title1: "ماذا يقول", titleHighlight: "عملاؤنا", desc: "رضا أولئك الذين عهدوا بسيارتهم إلى ميكانيكا النجار.", customer: "عميل النجار" },
    stats: { years: "سنوات من التقاليد", clients: "عملاء راضون", rating: "تقييم جوجل", guarantee: "أيام ضمان" },
    faq: { title1: "الأسئلة", titleHighlight: "الشائعة", desc: "أزل شكوكك حول خدماتنا وضماناتنا." },
    differentials: { title1: "لماذا تختار", titleHighlight: "النجار؟", desc: "ثقافتنا العربية تعلمنا معاملة كل عميل كضيف شرف." },
    howItWorks: { title1: "كيف", titleHighlight: "نعمل", desc: "عملية شفافة من البداية إلى النهاية." }
  }
};
